package models

import "time"

// ATSType identifies the Applicant Tracking System a company uses.
type ATSType string

const (
	ATSGreenhouse     ATSType = "greenhouse"
	ATSLever          ATSType = "lever"
	ATSAshby          ATSType = "ashby"
	ATSWorkday        ATSType = "workday"
	ATSSmartRecruiters ATSType = "smartrecruiters"
	ATSiCIMS          ATSType = "icims"
	ATSCustom         ATSType = "custom"
	ATSUnknown        ATSType = "unknown"
)

// Company is loaded from companies/seed_500.yaml.
type Company struct {
	Name              string   `yaml:"name"`
	Domain            string   `yaml:"domain"`
	ATS               ATSType  `yaml:"ats"`
	BoardID           string   `yaml:"board_id"`
	CareerURL         string   `yaml:"career_url"`
	VisaTransfersH1B  bool     `yaml:"visa_transfers_h1b"`
	SponsorsNewH1B    bool     `yaml:"sponsors_new_h1b"`
	Tier              int      `yaml:"tier"`
	Verified          bool     `yaml:"verified"`
	KeywordsInclude   []string `yaml:"keywords_include"`
	KeywordsExclude   []string `yaml:"keywords_exclude"`
	// Workday-specific
	WorkdayTenant     string   `yaml:"workday_tenant"`
	WorkdayBoard      string   `yaml:"workday_board"`
	WorkdayLocationIDs []string `yaml:"workday_location_ids"`
	// Custom scraper
	CustomModule      string            `yaml:"custom_module"`
	CustomParams      map[string]string `yaml:"custom_params"`
}

// Job is the normalised job posting schema across all ATS platforms.
// All connectors produce this struct.
type Job struct {
	// Identity
	ID       string  `json:"id"`        // UUID generated by scraper
	SourceID string  `json:"source_id"` // Native ATS job ID
	Source   ATSType `json:"source"`
	Company  string  `json:"company"`

	// Content
	Title           string `json:"title"`
	DescriptionHTML string `json:"description_html"`
	DescriptionText string `json:"description_text"` // HTML stripped
	URL             string `json:"url"`
	Location        string `json:"location"`
	Department      string `json:"department,omitempty"`
	Remote          bool   `json:"remote"`

	// Temporal
	PostedAt  *time.Time `json:"posted_at,omitempty"`
	ScrapedAt time.Time  `json:"scraped_at"`

	// Visa flags extracted from description (best-effort)
	MentionsSponsorship bool `json:"mentions_sponsorship"`
	NoSponsorshipPhrase bool `json:"no_sponsorship_phrase"`
}

// DedupeKey returns a stable key used for Redis SETNX deduplication.
func (j *Job) DedupeKey() string {
	return "job:" + string(j.Source) + ":" + j.SourceID
}

// ScrapeResult is what a connector returns for one company.
type ScrapeResult struct {
	Company  Company
	Jobs     []Job
	Error    error
	Duration float64 // seconds
}
